version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.4
    container_name: mariadb
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: rentorlend
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./rentorlend.sql:/docker-entrypoint-initdb.d/rentorlend.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  db_data: